[package]
name = "wer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
git2 = "0.18"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
